name: Gh-Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.3
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /cookup/
